# Generated by Django 2.0 on 2018-01-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0008_auto_20180120_0129'),
        ('guest', '0005_guestinfo_guest_info_field_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('num_of_draws', models.IntegerField()),
                ('label', models.CharField(max_length=500)),
                ('num_of_draws_done', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='RafflerSelectionWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.IntegerField()),
                ('guest_info_field', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffler.Raffler')),
            ],
        ),

        migrations.CreateModel(
            name='RafflerWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.Guest')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffler.Raffler')),
            ],
        ),
        migrations.AlterField(
            model_name='raffler',
            name='conditions',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='raffler',
            name='conditions',
            field=models.CharField(max_length=700),
        ),

    ]
