# Generated by Django 2.0 on 2018-01-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffler', '0002_auto_20180126_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffler',
            name='draw_duration',
            field=models.FloatField(default=5.2),
        ),
        migrations.AlterField(
            model_name='raffler',
            name='item_duration',
            field=models.FloatField(default=0.1),
        ),
    ]
