# Generated by Django 2.0 on 2018-01-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffler', '0003_auto_20180126_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffler',
            name='background_image',
            field=models.ImageField(default='Images/None/no.jpg', upload_to='Images/'),
        ),
        migrations.AddField(
            model_name='raffler',
            name='prize_image',
            field=models.ImageField(default='Images/None/no.jpg', upload_to='Images/'),
        ),
    ]
