# Generated by Django 2.0 on 2018-02-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffler', '0005_auto_20180201_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffler',
            name='conditions',
            field=models.CharField(default='No conditions defined', max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raffler',
            name='num_of_draws_done',
            field=models.IntegerField(default=0),
        ),
    ]
