# Generated by Django 2.0 on 2018-02-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffler', '0006_auto_20180201_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffler',
            name='conditions',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
