# Generated by Django 2.0 on 2018-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffler', '0007_auto_20180201_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffler',
            name='conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
