# Generated by Django 2.0 on 2018-01-02 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 2, 10, 32, 16, 690573), null=True)),
                ('end_date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 1, 2, 10, 32, 16, 690573), null=True)),
                ('venue', models.CharField(max_length=200)),
                ('facebook_url', models.CharField(max_length=200)),
                ('instagram_url', models.CharField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('no_of_guest', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 13, 14, 52, 756645)),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_of_guest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 13, 14, 52, 756645)),
        ),
        migrations.AlterField(
            model_name='event',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
