# Generated by Django 2.0 on 2018-01-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_guestinfo_guestinfofield'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinfofield',
            name='guest_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guest.Guest'),
        ),
        migrations.AddField(
            model_name='guestinfofield',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
