# Generated by Django 2.0 on 2018-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_guestinfo_guest_info_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestinfofield',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestinfofield',
            name='is_resolved',
            field=models.BooleanField(default=True),
        ),
    ]
