# Generated by Django 2.0 on 2018-02-07 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_auto_20180122_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
