# Generated by Django 2.0 on 2018-01-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0002_auto_20180102_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=200)),
                ('layout_type', models.IntegerField()),
                ('background_image', models.CharField(blank=True, max_length=200, null=True)),
                ('background_color', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_pos_x', models.FloatField()),
                ('logo_pos_y', models.FloatField()),
                ('logo_width', models.FloatField()),
                ('logo_height', models.FloatField()),
                ('canvas_height', models.FloatField()),
                ('canvas_width', models.FloatField()),
                ('canvas_padding', models.FloatField()),
                ('canvas_background_color', models.CharField(max_length=20)),
                ('canvas_opacity', models.FloatField()),
                ('canvas_pos_x', models.FloatField()),
                ('canvas_pos_y', models.FloatField()),
                ('button_image', models.CharField(blank=True, max_length=200, null=True)),
                ('button_color', models.CharField(max_length=20)),
                ('button_opacity', models.FloatField()),
                ('button_text_color', models.CharField(max_length=200)),
                ('submit_button_text', models.CharField(max_length=200)),
                ('next_button_text', models.CharField(max_length=200)),
                ('back_button_text', models.CharField(max_length=200)),
                ('button_font_family', models.CharField(max_length=50)),
                ('button_font_size', models.FloatField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
