# Generated by Django 2.0 on 2018-01-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0002_layoutfield_layoutfieldvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='layout',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
