# Generated by Django 2.0 on 2018-01-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0003_auto_20180120_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
