# Generated by Django 2.0 on 2018-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0004_auto_20180122_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutfield',
            name='label_font_family',
            field=models.CharField(default='Arial', max_length=100),
        ),
        migrations.AlterField(
            model_name='layout',
            name='button_font_size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='layout',
            name='button_opacity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_opacity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_padding',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_pos_x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_pos_y',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='canvas_width',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_pos_x',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_pos_y',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_width',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='font_size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='label_size',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='opacity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='order',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='page_num',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='layoutfield',
            name='width',
            field=models.CharField(max_length=200),
        ),
    ]
