# Generated by Django 2.0 on 2018-01-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0005_auto_20180125_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='layout_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
