# Generated by Django 2.0 on 2018-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0006_auto_20180126_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='logo_height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_pos_x',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_pos_y',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo_width',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
