# Generated by Django 2.0 on 2018-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0007_auto_20180126_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutfield',
            name='list_font_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layoutfield',
            name='list_font_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='layoutfield',
            name='list_font_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
