# Generated by Django 2.0 on 2018-01-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0008_auto_20180126_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='layout_type',
            field=models.IntegerField(default=0),
        ),
    ]
