# Generated by Django 2.0 on 2018-01-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0009_auto_20180126_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutfield',
            name='guest_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.GuestInfoField'),
        ),
    ]
