# Generated by Django 2.0 on 2018-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0010_auto_20180126_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='submit_button_image',
            field=models.ImageField(default='Images/None/no.jpg', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='background_image',
            field=models.ImageField(default='Images/None/no.jpg', upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo',
            field=models.ImageField(default='Images/None/no.jpg', upload_to='Images/'),
        ),
    ]
