# Generated by Django 2.0 on 2018-01-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0011_auto_20180127_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layout',
            name='submit_button_image',
        ),
    ]
