# Generated by Django 2.0 on 2018-02-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0012_remove_layout_submit_button_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='background_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo',
            field=models.TextField(),
        ),
    ]
