# Generated by Django 2.0 on 2018-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0013_auto_20180201_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='background_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
