# Generated by Django 2.0 on 2018-02-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0014_auto_20180201_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutfield',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
