# Generated by Django 2.0 on 2018-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0015_layoutfield_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='canvas_background_color',
            field=models.CharField(max_length=200),
        ),
    ]
