# Generated by Django 2.0 on 2018-02-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0016_auto_20180208_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layoutfield',
            name='guest_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='guest.GuestInfoField'),
        ),
    ]
