# Generated by Django 2.0 on 2017-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200, null=True)),
                ('facebook_url', models.CharField(max_length=200, null=True)),
                ('instagram_url', models.CharField(max_length=200, null=True)),
                ('twitter_url', models.CharField(max_length=200, null=True)),
                ('no_of_guest', models.IntegerField()),
            ],
        ),
    ]
